apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: newrelic/infrastructure-k8s-dev # Only suitable for local development since it does not really exists.
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
      - deploy/local.yaml
