---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: newrelic
rules:
- apiGroups: [""]
  resources:
    - "nodes"
    - "nodes/proxy"
    - "pods"
    - "services"
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: newrelic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic
subjects:
- kind: ServiceAccount
  name: newrelic
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: newrelic-infra
  namespace: kube-system
  labels:
    app: newrelic-infra
spec:
  selector:
    matchLabels:
      name: newrelic-infra
  template:
    metadata:
      labels:
        name: newrelic-infra
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"operator": "Exists", "effect": "NoSchedule"}]
    spec:
      serviceAccountName: newrelic
      containers:
        - name: newrelic-infra
          image: newrelic/ohaik:1.0.0-beta3
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /host
              name: host-volume
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: host-docker-socket
          env:
            - name: CLUSTER_NAME
              value: <YOUR_CLUSTER_NAME>
            - name: NRIA_LICENSE_KEY
              value: <YOUR_LICENSE_KEY>
            - name: NRIA_DISPLAY_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NRIA_PASSTHROUGH_ENVIRONMENT
              value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME"
      volumes:
        - name: host-volume
          hostPath:
            path: /
        - name: host-docker-socket
          hostPath:
            path: /var/run/docker.sock
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"