---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-tests-pv-claim-{{ .Release.Name }}
  labels:
    app: e2e-tests
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
