dependencies:
  - name: kube-state-metrics
    version: "0.7.1"
    repository: "@stable"
    alias: ksm-instance-one
    tags:
      - one-ksm-instance
      - two-ksm-instances

  - name: kube-state-metrics
    version: "0.7.1"
    repository: "@stable"
    alias: ksm-instance-two
    tags:
      - two-ksm-instances
