name: E2E over minikube

on:
  push:
    branches: [ feat/movePipelines ]
  pull_request:
    branches: [ feat/movePipelines ]

jobs:
  e2eTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        priviledgeMode: [ "normal", "unprivileged" ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.4'
    - name: Setup Helm and Socat
      run: |
        curl https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz --output helm.tar.gz
        tar -zxvf helm.tar.gz
        sudo apt-get update -y
        sudo apt-get install -y socat
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.0.1
      with:
        minikube version: 'v1.14.2'
        kubernetes version: 'v1.19.2'
    - name: Compile and Build Image
      run: |
        make compile
        eval $(minikube docker-env)
        docker build -t test_image_${{ matrix.priviledgeMode }}:test .
    - name: Interact with the cluster
      run: |
        if [ "${{ matrix.priviledgeMode }}" = "unprivileged" ]; then
          UNPRIVILEDGE=true
        else
          UNPRIVILEDGE=false
        fi
        go run e2e/cmd/e2e.go --verbose --cluster_name=e2e --nr_license_key="fakeLicense" --rbac=true --integration_image_tag=test --integration_image_repository=test_image_${{ matrix.priviledgeMode }} --unprivileged=$UNPRIVILEDGE
