name: E2E over minikube

on:
  push:
    branches: [ feat/movePipelines ]
  pull_request:
    branches: [ feat/movePipelines ]
jobs:
  e2eTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.4'
    - name: Setup Helm
      run: |
        curl https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz --output helm.tar.gz
        tar -zxvf helm.tar.gz
        linux-amd64/helm version
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.0.1
      with:
        minikube version: 'v1.14.2'
        kubernetes version: 'v1.19.2'
    - name: Interact with the cluster
      run: CLUSTER_NAME=e2e NR_LICENSE_KEY=fakeLicense  go run e2e/cmd/e2e.go --verbose --rbac=true --integration_image_tag=1.26.6